/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE organismeBaseService PLEASE EDIT ../organisme.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Organisme } from '../../domain/manage_film_example_db/organisme';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../organisme.service.ts
 */

/*
 * SCHEMA DB organisme
 *
	{
		code: {
			type: 'Number',
			required : true
		},
		liballe: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		organisme_user: {
			type: Schema.ObjectId,
			ref : "organisme"
		},
	}
 *
 */
@Injectable()
export class OrganismeBaseService {

    contextUrl: string = environment.endpoint + '/organisme';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * organismeService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Organisme): Observable<Organisme> {
        return this.http
            .post<Organisme>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * organismeService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * organismeService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Organisme> {
        return this.http
            .get<Organisme>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * organismeService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Organisme[]> {
        return this.http
            .get<Organisme[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * organismeService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Organisme): Observable<Organisme> {
        return this.http
            .post<Organisme>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
